"""Every stat the site can show: column -> label, format, group, and whether higher is better.
Formats: i=integer, 1=one decimal, 2=two decimals, 3=three decimals, p=percentage."""

PLAYER_STATS = {
    # Basic per game
    "gp": ("GP", "i", "Basic", True),
    "min_pg": ("MIN", "1", "Basic", True),
    "pts_pg": ("PTS", "1", "Basic", True),
    "reb_pg": ("REB", "1", "Basic", True),
    "ast_pg": ("AST", "1", "Basic", True),
    "stl_pg": ("STL", "1", "Basic", True),
    "blk_pg": ("BLK", "1", "Basic", True),
    "tov_pg": ("TOV", "1", "Basic", False),
    "oreb_pg": ("OREB", "1", "Basic", True),
    "dreb_pg": ("DREB", "1", "Basic", True),
    "fg3m_pg": ("3PM", "1", "Basic", True),
    "pf_pg": ("PF", "1", "Basic", False),
    "plus_minus": ("+/-", "i", "Basic", True),
    "dd2": ("Double-doubles", "i", "Basic", True),
    "td3": ("Triple-doubles", "i", "Basic", True),
    # Totals
    "min": ("Minutes", "i", "Totals", True),
    "pts": ("Points", "i", "Totals", True),
    "reb": ("Rebounds", "i", "Totals", True),
    "ast": ("Assists", "i", "Totals", True),
    "stl": ("Steals", "i", "Totals", True),
    "blk": ("Blocks", "i", "Totals", True),
    "fg3m": ("3-pointers made", "i", "Totals", True),
    "ftm": ("Free throws made", "i", "Totals", True),
    # Shooting
    "fg_pct": ("FG%", "p", "Shooting", True),
    "fg2_pct": ("2P%", "p", "Shooting", True),
    "fg3_pct": ("3P%", "p", "Shooting", True),
    "ft_pct": ("FT%", "p", "Shooting", True),
    "efg_pct": ("eFG%", "p", "Shooting", True),
    "ts_pct": ("TS%", "p", "Shooting", True),
    "fg3a_rate": ("3PA rate", "p", "Shooting", None),
    "fta_rate": ("FTA rate", "p", "Shooting", True),
    "fga_pg": ("FGA", "1", "Shooting", None),
    "fg3a_pg": ("3PA", "1", "Shooting", None),
    "fta_pg": ("FTA", "1", "Shooting", True),
    # Per 36
    "pts_p36": ("PTS/36", "1", "Per 36", True),
    "reb_p36": ("REB/36", "1", "Per 36", True),
    "ast_p36": ("AST/36", "1", "Per 36", True),
    "stl_p36": ("STL/36", "1", "Per 36", True),
    "blk_p36": ("BLK/36", "1", "Per 36", True),
    "tov_p36": ("TOV/36", "1", "Per 36", False),
    # Per 100
    "pts_p100": ("PTS/100", "1", "Per 100", True),
    "reb_p100": ("REB/100", "1", "Per 100", True),
    "ast_p100": ("AST/100", "1", "Per 100", True),
    "stl_p100": ("STL/100", "1", "Per 100", True),
    "blk_p100": ("BLK/100", "1", "Per 100", True),
    "tov_p100": ("TOV/100", "1", "Per 100", False),
    "fg3a_p100": ("3PA/100", "1", "Per 100", None),
    "fta_p100": ("FTA/100", "1", "Per 100", True),
    # Advanced (NBA.com)
    "usg_pct": ("USG%", "p", "Advanced", None),
    "ast_pct": ("AST%", "p", "Advanced", True),
    "oreb_pct": ("OREB%", "p", "Advanced", True),
    "dreb_pct": ("DREB%", "p", "Advanced", True),
    "reb_pct": ("REB%", "p", "Advanced", True),
    "tm_tov_pct": ("TOV%", "1", "Advanced", False),
    "ast_tov": ("AST/TO", "2", "Advanced", True),
    "off_rating": ("ORtg", "1", "Advanced", True),
    "def_rating": ("DRtg", "1", "Advanced", False),
    "net_rating": ("Net Rtg", "1", "Advanced", True),
    "pie": ("PIE", "p", "Advanced", True),
    "pace": ("Pace", "1", "Advanced", None),
    "per_calc": ("PER (ours)", "1", "Advanced", True),
    "gmsc_avg": ("Game Score", "1", "Advanced", True),
    # Impact (Basketball Reference + on/off)
    "per": ("PER", "1", "Impact", True),
    "ws": ("Win Shares", "1", "Impact", True),
    "ows": ("OWS", "1", "Impact", True),
    "dws": ("DWS", "1", "Impact", True),
    "ws_per_48": ("WS/48", "3", "Impact", True),
    "bpm": ("BPM", "1", "Impact", True),
    "obpm": ("OBPM", "1", "Impact", True),
    "dbpm": ("DBPM", "1", "Impact", True),
    "vorp": ("VORP", "1", "Impact", True),
    "stl_pct": ("STL%", "1", "Impact", True),
    "blk_pct": ("BLK%", "1", "Impact", True),
    "on_net_rating": ("On-court net", "1", "Impact", True),
    "off_net_rating": ("Off-court net", "1", "Impact", None),
    "net_diff": ("On/off net", "1", "Impact", True),
    "ortg_diff": ("On/off ORtg", "1", "Impact", True),
    "drtg_diff": ("On/off DRtg", "1", "Impact", False),
    # Shot zones (NBA.com shot locations)
    "ra_share": ("Rim share", "p", "Shot zones", None),
    "paint_share": ("Paint share", "p", "Shot zones", None),
    "mid_share": ("Mid-range share", "p", "Shot zones", None),
    "c3_share": ("Corner 3 share", "p", "Shot zones", None),
    "atb3_share": ("Above-break 3 share", "p", "Shot zones", None),
    "ra_fg_pct": ("Rim FG%", "p", "Shot zones", True),
    "paint_fg_pct": ("Paint FG%", "p", "Shot zones", True),
    "mid_fg_pct": ("Mid-range FG%", "p", "Shot zones", True),
    "c3_fg_pct": ("Corner 3 FG%", "p", "Shot zones", True),
    "atb3_fg_pct": ("Above-break 3 FG%", "p", "Shot zones", True),
    # Clutch: last 5 minutes, score within 5
    "clutch_min": ("Clutch MIN", "i", "Clutch", True),
    "clutch_pts": ("Clutch PTS", "i", "Clutch", True),
    "clutch_pts_p36": ("Clutch PTS/36", "1", "Clutch", True),
    "clutch_ts_pct": ("Clutch TS%", "p", "Clutch", True),
    "clutch_plus_minus": ("Clutch +/-", "i", "Clutch", True),
    # Hustle (2015-16 onward)
    "deflections_p36": ("Deflections/36", "1", "Hustle", True),
    "contested_shots_p36": ("Contests/36", "1", "Hustle", True),
    "screen_assists_p36": ("Screen assists/36", "1", "Hustle", True),
    "loose_balls_recovered_p36": ("Loose balls/36", "1", "Hustle", True),
    "box_outs_p36": ("Box outs/36", "1", "Hustle", True),
    "charges_drawn": ("Charges drawn", "i", "Hustle", True),
    # Impact models (ours): lineup RAPM, box model, prior-informed RAPM, wins above replacement
    "impact": ("Impact", "1", "Impact models", True),
    "o_impact": ("O-Impact", "1", "Impact models", True),
    "d_impact": ("D-Impact", "1", "Impact models", True),
    "war": ("WAR", "1", "Impact models", True),
    "box_impact": ("Box Impact", "1", "Impact models", True),
    "o_box": ("O-Box", "1", "Impact models", True),
    "d_box": ("D-Box", "1", "Impact models", True),
    "rapm": ("RAPM (pure)", "1", "Impact models", True),
    "rapm_o": ("O-RAPM", "1", "Impact models", True),
    "rapm_d": ("D-RAPM", "1", "Impact models", True),
    # Shot quality
    "xefg_pct": ("Expected eFG%", "p", "Shot quality", None),
    "shot_making": ("Shot-making (eFG - xeFG)", "p", "Shot quality", True),
    "ts_rel": ("Relative TS%", "p", "Shot quality", True),
    "scoring_value": ("Scoring value (pts vs avg)", "1", "Shot quality", True),
    # Consistency
    "gmsc_sd": ("Game Score SD", "1", "Consistency", None),
    "gmsc_p10": ("Floor (10th pct GmSc)", "1", "Consistency", True),
    "gmsc_p90": ("Ceiling (90th pct GmSc)", "1", "Consistency", True),
    "consistency": ("Consistency (mean/SD)", "2", "Consistency", True),
    # Bio
    "height_in": ("Height (in)", "i", "Bio", None),
    "weight": ("Weight (lb)", "i", "Bio", None),
    "draft_number": ("Draft pick", "i", "Bio", False),
}

TEAM_STATS = {
    "w": ("W", "i", "Record", True),
    "l": ("L", "i", "Record", False),
    "w_pct": ("Win%", "3", "Record", True),
    "pyth_w": ("Pythag W", "1", "Record", True),
    "luck": ("Luck (W - Pythag)", "1", "Record", None),
    "pts_pg": ("PTS", "1", "Scoring", True),
    "opp_pts_pg": ("Opp PTS", "1", "Scoring", False),
    "reb_pg": ("REB", "1", "Scoring", True),
    "ast_pg": ("AST", "1", "Scoring", True),
    "tov_pg": ("TOV", "1", "Scoring", False),
    "fg3a_pg": ("3PA", "1", "Scoring", None),
    "fg_pct": ("FG%", "p", "Shooting", True),
    "fg3_pct": ("3P%", "p", "Shooting", True),
    "ts_pct": ("TS%", "p", "Shooting", True),
    "efg_pct": ("eFG%", "p", "Four factors", True),
    "tm_tov_pct": ("TOV%", "p", "Four factors", False),
    "oreb_pct": ("OREB%", "p", "Four factors", True),
    "fta_rate": ("FT rate", "3", "Four factors", True),
    "opp_efg_pct": ("Opp eFG%", "p", "Four factors", False),
    "opp_tov_pct": ("Opp TOV%", "p", "Four factors", True),
    "opp_oreb_pct": ("Opp OREB%", "p", "Four factors", False),
    "opp_fta_rate": ("Opp FT rate", "3", "Four factors", False),
    "off_rating": ("ORtg", "1", "Ratings", True),
    "def_rating": ("DRtg", "1", "Ratings", False),
    "net_rating": ("Net Rtg", "1", "Ratings", True),
    "pace": ("Pace", "1", "Ratings", None),
    "fg3a_rate": ("3PA rate", "p", "Ratings", None),
    "srs": ("SRS", "2", "Power", True),
    "mov": ("Margin", "1", "Power", True),
    "sos": ("Strength of schedule", "2", "Power", None),
    "elo_end": ("Elo (end)", "i", "Power", True),
    "elo_peak": ("Elo (peak)", "i", "Power", True),
}

LEAGUE_STATS = {
    "pts_pg": ("Points per team game", "1"),
    "pace": ("Pace", "1"),
    "ortg": ("Offensive rating", "1"),
    "ts_pct": ("True shooting %", "p"),
    "efg_pct": ("Effective FG %", "p"),
    "fg3a_rate": ("3-point attempt rate", "p"),
    "fg3a_pg": ("3PA per team game", "1"),
    "fg3_pct": ("3P%", "p"),
    "fta_rate": ("FTA rate", "p"),
    "ast_pg": ("Assists per team game", "1"),
    "tov_pg": ("Turnovers per team game", "1"),
    "oreb_pg": ("Off. rebounds per team game", "1"),
}


def as_json(d):
    return {k: {"label": v[0], "fmt": v[1], "group": v[2] if len(v) > 2 else None,
                "better": v[3] if len(v) > 3 else True} for k, v in d.items()}
